# Example parameter file, see parameters_launch.py

# Format is namespace_name/node_name
arducam/gscam_publisher:
  ros__parameters:
    gscam_config: 'nvarguscamerasrc ! nvvidconv ! videoconvert'
    preroll: False
    use_gst_timestamps: False
    frame_id: 'arducam'
